#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source "$(dirname "$0")/common.sh"

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload=$(mktemp "${TMPDIR}/gitlab-merge-request-resource.XXXXXX")

cat > "${payload}" <&0

gitlab_host=$(jq -r '.source.gitlab_host // ""' < "${payload}")
private_token=$(jq -r '.source.private_token // ""' < "${payload}")
project_path=$(jq -r '.source.project_path // ""' < "${payload}")
username=$(jq -r '.source.username // ""' < "${payload}")
password=$(jq -r '.source.password // ""' < "${payload}")
version=$(jq -r '.version // ""' < "${payload}")
mr_id=$(jq -r '.version.mr_id // ""' < "${payload}")

project_path="${project_path//'/'/'%2F'}" # url encode "/"

merge_request=$(curl \
--header "PRIVATE-TOKEN: ${private_token}" \
"https://${gitlab_host}/api/v3/projects/${project_path}/merge_requests/${mr_id}")

source_branch="$(echo ${merge_request} | jq -r '.source_branch // ""')"

uri="https://${username}:${password}@${gitlab_host}/${project_path}.git"

if [ -z "${version}" ]; then
  version='{"updated_at":"1800-01-01T00:00:00.000Z","sha":null}'
fi

branch_flag=""
if ! [ -z "${source_branch}" ]; then
  branch_flag="--branch ${source_branch}"
fi

git clone --single-branch "${uri}" ${branch_flag} "${destination}"

echo "${mr_id}" > "${destination}/merge-request-id"

cd "${destination}"

jq -n "{
  version: ${version},
  metadata: $(git_metadata)
}" >&3
