#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload=$(mktemp "${TMPDIR}/gitlab-merge-request-resource.XXXXXX")

cat > "${payload}" <&0

gitlab_host=$(jq -r '.source.gitlab_host // ""' < "${payload}")
username=$(jq -r '.source.username // ""' < "${payload}")
password=$(jq -r '.source.password // ""' < "${payload}")
project_path=$(jq -r '.source.project_path // ""' < "${payload}")
version=$(jq -r '.version // ""' < "${payload}")
source_branch=$(jq -r '.version.source_branch // ""' < "${payload}")

uri="https://${username}:${password}@${gitlab_host}/${project_path}.git"

git clone --single-branch "${uri}" --branch "${source_branch}" "${destination}"

echo "{ \"version\": ${version} }"
