#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source "$(dirname "$0")/common.sh"

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload=$(mktemp "${TMPDIR}/gitlab-merge-request-resource.XXXXXX")

cat > "${payload}" <&0

version=$(jq -r '.version // ""' < "${payload}")

if [ -z "${version}" ]; then
  version='{"updated_at":"1800-01-01T00:00:00.000Z","sha":null}'
fi

cd "${destination}"

jq -n "{
  version: ${version},
  metadata: $(git_metadata)
}" >&3
